# This file was generated by GoReleaser. DO NOT EDIT.
cask "privatebox" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "5f28ee37d88452c5d0dda3a24afdd0d929b8898d4f821488626792f206fae740"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7813c2ba35926903280dffd1e61a0d078858532e65dbe867c25577cb838f4ee4"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4191232c88a7cbcbba5bdf768885240579108c2fddc1183aa752f806ea8243b"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00f5732683d77751f05f818b8cb635734588c71ba2bfd9e0764b50a4978aa409"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "privatebox"
  desc "Command-line client for the PrivateBox API"
  homepage "https://www.privatebox.co.nz/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "privatebox"

  # No zap stanza required
end
