# This file was generated by GoReleaser. DO NOT EDIT.
cask "privatebox" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "91c565af44b44ad535ecc60b5e30f4f392343c76ff6167fa8a6ac4e03c932fbe"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a38f52f863fb81615ec7960f87819476f42bbba52e66d05327e4c67b1243fe24"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbe138dc01210e9f40de9312b27d16e2ab5ac70e8e8159d4469e5673b14799c0"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f95744252fc2215d980ae5b57bf26559869ca6469f601f1020114095aa61d22"
      url "https://github.com/privatebox/privatebox-cli/releases/download/v#{version}/privatebox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "privatebox"
  desc "Command-line client for the PrivateBox API"
  homepage "https://www.privatebox.co.nz/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "privatebox"

  # No zap stanza required
end
